version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.11
      - test-3.10
      - test-3.9
      - test-3.8
      - test-3.7
      - test-3.6
jobs:
  test-3.11: &test-template
    docker:
      - image: cimg/python:3.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-3.11-dependencies-{{ checksum "setup.py" }}
          - v1-3.11-dependencies-
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install graphviz nodejs npm libnss3 libgtk-3-0 libasound2 libgtk2.0-0 libgconf-2-4 chromium-browser xvfb
            sudo npm install -g electron@6.1.4 orca
            python3 -m pip install --user --upgrade pip
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -e '.[test,graph,spss]'
      - save_cache:
          paths:
            - ./venv
          key: v1-3.11-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest --cov
  test-3.10: &test-template
    docker:
      - image: cimg/python:3.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-3.10-dependencies-{{ checksum "setup.py" }}
          - v1-3.10-dependencies-
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install graphviz nodejs npm libnss3 libgtk-3-0 libasound2 libgtk2.0-0 libgconf-2-4 chromium-browser xvfb
            sudo npm install -g electron@6.1.4 orca
            python3 -m pip install --user --upgrade pip
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -e '.[test,graph,spss]'
      - save_cache:
          paths:
            - ./venv
          key: v1-3.10-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
  test-3.9: &test-template
    docker:
      - image: cimg/python:3.9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-3.9-dependencies-{{ checksum "setup.py" }}
          - v1-3.9-dependencies-
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install graphviz nodejs npm libnss3 libgtk-3-0 libasound2 libgtk2.0-0 libgconf-2-4 chromium-browser xvfb
            sudo npm install -g electron@6.1.4 orca
            python3 -m pip install --user --upgrade pip
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -e '.[test,graph,spss]'
      - save_cache:
          paths:
            - ./venv
          key: v1-3.9-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
  test-3.8: &test-template
    docker:
      - image: cimg/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-3.8-dependencies-{{ checksum "setup.py" }}
          - v1-3.8-dependencies-
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install graphviz nodejs npm libnss3 libgtk-3-0 libasound2 libgtk2.0-0 libgconf-2-4 chromium-browser xvfb
            sudo npm install -g electron@6.1.4 orca
            python3 -m pip install --user --upgrade pip
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -e '.[test,graph,spss]'
      - save_cache:
          paths:
            - ./venv
          key: v1-3.8-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
  test-3.7: &test-template
    docker:
      - image: cimg/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-3.7-dependencies-{{ checksum "setup.py" }}
          - v1-3.7-dependencies-
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install graphviz nodejs npm libnss3 libgtk-3-0 libasound2 libgtk2.0-0 libgconf-2-4 chromium-browser xvfb
            sudo npm install -g electron@6.1.4 orca
            python3 -m pip install --user --upgrade pip
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -e '.[test,graph,spss]'
      - save_cache:
          paths:
            - ./venv
          key: v1-3.7-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
  test-3.6: &test-template
    docker:
      - image: cimg/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-3.6-dependencies-{{ checksum "setup.py" }}
          - v1-3.6-dependencies-
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install graphviz nodejs npm libnss3 libgtk-3-0 libasound2 libgtk2.0-0 libgconf-2-4 chromium-browser xvfb
            sudo npm install yarn -g
            sudo yarn global add electron@6.1.4 orca
            python3 -m pip install --user --upgrade pip
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -e '.[test,graph,spss]'
      - save_cache:
          paths:
            - ./venv
          key: v1-3.6-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
