version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.8
      - test-3.7
      - test-3.6
jobs:
  test-3.8: &test-template
    docker:
      - image: circleci/python:3.8.1-buster
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m pip install --user --upgrade pip
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -e '.[test]'
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest --cov=CHAID/
            codecov --token=be8cd1f6-1560-4628-8a34-b557a119894b
  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7.6-buster
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m pip install --user --upgrade pip
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -e '.[test]'
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6.9-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m pip install --user --upgrade pip
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -e '.[test]'
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
